import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { getSession, signOut } from "next-auth/react";
import Button from "@/components/Button";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <div className="w-full h-40 text-center flex flex-col justify-center items-center ">
          <div className="text-3xl">SHELTRANCE</div>
          <Button onClick={logoutHandler} color="bg-red-500">
            wyloguj
          </Button>
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps(context: any) {
  const session = await getSession({ req: context.req });

  if (!session) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
  return { props: {} };
}

const logoutHandler = () => {
  signOut();
};
